//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionBefore4Weeks
    {
        public int MarketActionId { get; set; }
        public string ActivityBackground { get; set; }
        public string ActivityObjective { get; set; }
        public string ActivityDesc { get; set; }
        public Nullable<int> People_ParticipantsCount { get; set; }
        public Nullable<int> People_DCPIDCount { get; set; }
        public Nullable<int> People_NewLeadsThisYearCount { get; set; }
        public Nullable<int> People_InvitationTotalCount { get; set; }
        public Nullable<int> People_InvitationCarOwnerCount { get; set; }
        public Nullable<int> People_InvitationDepositorCount { get; set; }
        public Nullable<int> People_InvitationPotentialCount { get; set; }
        public Nullable<int> People_InvitationOtherCount { get; set; }
        public string Vehide_Usage { get; set; }
        public string Vehide_Model { get; set; }
        public Nullable<int> Vehide_Qty { get; set; }
        public Nullable<decimal> TotalBudgetAmt { get; set; }
        public Nullable<decimal> CoopFundSumAmt { get; set; }
        public string KeyVisionPic { get; set; }
        public string KeyVisionDesc { get; set; }
        public string KeyVisionApprovalCode { get; set; }
        public string KeyVisionApprovalDesc { get; set; }
        public Nullable<decimal> ProcessPercent { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
