//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionAfter7CoopFund
    {
        public int MarketActionId { get; set; }
        public int SeqNO { get; set; }
        public string CoopFundCode { get; set; }
        public Nullable<decimal> CoopFundAmt { get; set; }
        public Nullable<bool> CoopFund_DMFChk { get; set; }
        public string CoopFundDesc { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
    }
}
