//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionAfter7
    {
        public int MarketActionId { get; set; }
        public string HightLights { get; set; }
        public string ImproveArea { get; set; }
        public string CustomerFeedback { get; set; }
        public string MarketSaleTeamAdvice { get; set; }
        public Nullable<int> People_ParticipantsCount { get; set; }
        public Nullable<int> People_DCPIDCount { get; set; }
        public Nullable<int> People_NewLeadsThsYearCount { get; set; }
        public Nullable<int> People_ActualArrivalCount { get; set; }
        public Nullable<int> People_ActualCarOwnerCount { get; set; }
        public Nullable<int> People_ActualDepositorCount { get; set; }
        public Nullable<int> People_ActualPotentialCount { get; set; }
        public Nullable<int> People_OthersCount { get; set; }
        public string Platform_Media { get; set; }
        public string Platform_ExposuerForm { get; set; }
        public Nullable<decimal> TotalBudgetAmt { get; set; }
        public Nullable<decimal> CoopFundSumAmt { get; set; }
        public Nullable<decimal> ProcessPercent { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
